@startuml

skinparam packageStyle rectangle
skinparam ClassFontSize 20
skinparam ClassAttributeFontSize 18
skinparam titleBorderRoundCorner 26
'skinparam PackageFontSize 38
skinparam titleBorderThickness 2
skinparam titleBorderColor red
skinparam titleBackgroundColor Cornsilk
skinparam LegendFontSize 8
title smart-socket 内存池

package org.smart.socket.buffer <<Frame>> {

note "提供堆外缓冲区 DirectByteBuffer 的池化服务，\n由内存池管理虚拟内存块 VirtualBuffer 的分配与回收" as tip

class BufferPage {
 - List<VirtualBuffer> freeList
 - ByteBuffer buffer
 + VirtualBuffer allocate(int size)
 void clean(VirtualBuffer cleanBuffer)
}


class BufferPagePool {
- BufferPage[] bufferPageList
'- int cursor
+ allocateBufferPage()
}


class VirtualBuffer{
   BufferPage bufferPage
   - ByteBuffer buffer
   - boolean clean
   - int parentPosition
   - int parentLimit

   + ByteBuffer buffer()
   + void clean()
}

BufferPagePool "1" *--  "N" BufferPage : 缓存页池化
BufferPage "1" *- "0..*" VirtualBuffer : 虚拟内存块
}
'org.smart.socket +-- org.smart.socket.transport

'org.smart.socket.transport +-- org.smart.socket.buffer

legend right
  三刀
endlegend

@enduml